mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: site.jaedoo.mygeorecord
  configuration:
    map-underscore-to-camel-case: on

spring:

  datasource:
    url: jdbc:h2:mem:testDB

  h2:
    console:
      enabled: true

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql